version: "3.7"

services:
  export-html:
    container_name: export-html
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "2305:2305"
